"""changed media_url to object_key

Revision ID: 189444290430
Revises: ced3435b986e
Create Date: 2026-05-09 10:20:17.248584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189444290430'
down_revision: Union[str, Sequence[str], None] = 'ced3435b986e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('object_key', sa.String(length=1000), nullable=False))
    op.drop_column('post_media', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('media_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('post_media', 'object_key')
    # ### end Alembic commands ###
