"""added sid in refreshtoken table

Revision ID: 1a2da454d2dc
Revises: b58d38265ad0
Create Date: 2026-05-03 00:24:07.924132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2da454d2dc'
down_revision: Union[str, Sequence[str], None] = 'b58d38265ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('sid', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_sid'), 'refresh_tokens', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_sid'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'sid')
    # ### end Alembic commands ###
