"""added purging in user model

Revision ID: 20a77f92753d
Revises: bd9052613855
Create Date: 2026-06-21 11:37:49.957130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a77f92753d'
down_revision: Union[str, Sequence[str], None] = 'bd9052613855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('purge_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_deletion_scheduled_for'), 'users', ['deletion_scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deletion_scheduled_for'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'purged_at')
    op.drop_column('users', 'purge_started_at')
    op.drop_column('users', 'deletion_scheduled_for')
    # ### end Alembic commands ###
