"""added nullable=false in created_at in refreshtoken_table

Revision ID: 3372aaa5ce74
Revises: ee13bc83d5f6
Create Date: 2026-05-04 17:10:55.746216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3372aaa5ce74'
down_revision: Union[str, Sequence[str], None] = 'ee13bc83d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
