"""added pre_deletion_status in user model

Revision ID: 389408687768
Revises: e0edb03d5305
Create Date: 2026-06-21 11:59:52.285744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389408687768'
down_revision: Union[str, Sequence[str], None] = 'e0edb03d5305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pre_deletion_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pre_deletion_status')
    # ### end Alembic commands ###
