"""added index for fast search in refreshtoken and removed index=true from those columns

Revision ID: 4a12f74364f8
Revises: 1a2da454d2dc
Create Date: 2026-05-04 16:48:08.665053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a12f74364f8'
down_revision: Union[str, Sequence[str], None] = '1a2da454d2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_sid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index('idx_refresh_sid', 'refresh_tokens', ['sid'], unique=False)
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_sid', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_sid'), 'refresh_tokens', ['sid'], unique=False)
    # ### end Alembic commands ###
