"""added bio,profile,follower/following counts in user table

Revision ID: 55dae9cbb2ba
Revises: a351bd5c05e7
Create Date: 2026-04-27 19:22:25.965437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dae9cbb2ba'
down_revision: Union[str, Sequence[str], None] = 'a351bd5c05e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('follower_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('following_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
