"""updated post table and created new table post_media

Revision ID: 7585d482929f
Revises: 3372aaa5ce74
Create Date: 2026-05-05 16:26:41.828387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7585d482929f'
down_revision: Union[str, Sequence[str], None] = '3372aaa5ce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
