"""added_password_reset_token_table

Revision ID: 769ed5c014c6
Revises: f3d38d9ddcaa
Create Date: 2026-04-26 20:24:01.960258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769ed5c014c6'
down_revision: Union[str, Sequence[str], None] = 'f3d38d9ddcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
