"""added index constraint to follow table

Revision ID: 9eef38aa5347
Revises: 9ff8fff58400
Create Date: 2026-05-03 00:10:07.103451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eef38aa5347'
down_revision: Union[str, Sequence[str], None] = '9ff8fff58400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index('ix_follows_following_created_follower', 'follows', ['following_id', 'created_at', 'follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_following_created_follower', table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    # ### end Alembic commands ###
