"""updated user table and added follow table

Revision ID: accad4644912
Revises: 6726b1083976
Create Date: 2026-04-27 17:32:24.364060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accad4644912'
down_revision: Union[str, Sequence[str], None] = '6726b1083976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
