"""added sid in follow table

Revision ID: b58d38265ad0
Revises: 9eef38aa5347
Create Date: 2026-05-03 00:19:06.100712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58d38265ad0'
down_revision: Union[str, Sequence[str], None] = '9eef38aa5347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('sid', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_follows_sid'), 'follows', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follows_sid'), table_name='follows')
    op.drop_column('follows', 'sid')
    # ### end Alembic commands ###
