"""added like related columns in post, user, and made post_like table

Revision ID: bd9052613855
Revises: c496adf6abea
Create Date: 2026-05-27 13:06:17.974739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9052613855'
down_revision: Union[str, Sequence[str], None] = 'c496adf6abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like_post_user')
    )
    op.create_index('idx_post_likes_post_created', 'post_likes', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_post_likes_user_created', 'post_likes', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_likes_user_created', table_name='post_likes')
    op.drop_index('idx_post_likes_post_created', table_name='post_likes')
    op.drop_table('post_likes')
    # ### end Alembic commands ###
