"""added is_private and accepted column to user and follow table for private accts

Revision ID: c496adf6abea
Revises: 340a99a99238
Create Date: 2026-05-19 15:14:33.542159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c496adf6abea'
down_revision: Union[str, Sequence[str], None] = '340a99a99238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('accepted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_private')
    op.drop_column('follows', 'accepted')
    # ### end Alembic commands ###
