"""updated post and media table

Revision ID: ced3435b986e
Revises: e3ef5906a950
Create Date: 2026-05-05 17:33:40.800937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced3435b986e'
down_revision: Union[str, Sequence[str], None] = 'e3ef5906a950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_media', 'media_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.create_index('idx_post_media_post_order', 'post_media', ['post_id', 'order_index'], unique=False)
    op.create_unique_constraint('uq_post_media_order', 'post_media', ['post_id', 'order_index'])
    op.drop_constraint(op.f('post_media_post_id_fkey'), 'post_media', type_='foreignkey')
    op.create_foreign_key(None, 'post_media', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('posts', sa.Column('visibility', sa.String(), server_default=sa.text("'public'"), nullable=False))
    op.drop_index(op.f('idx_post_status'), table_name='posts')
    op.drop_index(op.f('idx_post_user'), table_name='posts')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.create_index('idx_post_user_created', 'posts', ['author_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('idx_post_user_created', table_name='posts')
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_post_user'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_post_status'), 'posts', ['status'], unique=False)
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'author_id')
    op.drop_constraint(None, 'post_media', type_='foreignkey')
    op.create_foreign_key(op.f('post_media_post_id_fkey'), 'post_media', 'posts', ['post_id'], ['id'])
    op.drop_constraint('uq_post_media_order', 'post_media', type_='unique')
    op.drop_index('idx_post_media_post_order', table_name='post_media')
    op.alter_column('post_media', 'media_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
