"""added enum so changed post columns

Revision ID: d839994615c2
Revises: 7e02e7677179
Create Date: 2026-05-18 12:17:14.408132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd839994615c2'
down_revision: Union[str, Sequence[str], None] = '7e02e7677179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_uploads', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('idx_upload_status_created', 'media_uploads', ['status', 'created_at'], unique=False)
    op.drop_column('media_uploads', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_uploads', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('idx_upload_status_created', table_name='media_uploads')
    op.drop_column('media_uploads', 'created_at')
    # ### end Alembic commands ###
