"""added userdeletionaudit model

Revision ID: e0edb03d5305
Revises: 20a77f92753d
Create Date: 2026-06-21 11:45:01.112376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0edb03d5305'
down_revision: Union[str, Sequence[str], None] = '20a77f92753d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_deletion_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deletion_audit_created_at'), 'user_deletion_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_deletion_audit_event_type'), 'user_deletion_audit', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_deletion_audit_user_id'), 'user_deletion_audit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deletion_audit_user_id'), table_name='user_deletion_audit')
    op.drop_index(op.f('ix_user_deletion_audit_event_type'), table_name='user_deletion_audit')
    op.drop_index(op.f('ix_user_deletion_audit_created_at'), table_name='user_deletion_audit')
    op.drop_table('user_deletion_audit')
    # ### end Alembic commands ###
