"""added index for fast search in follow table and removed index=true from those columns

Revision ID: ee13bc83d5f6
Revises: 4a12f74364f8
Create Date: 2026-05-04 16:58:59.502303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee13bc83d5f6'
down_revision: Union[str, Sequence[str], None] = '4a12f74364f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.create_index('ix_follows_follower_created_following', 'follows', ['follower_id', 'created_at', 'following_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_follower_created_following', table_name='follows')
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    # ### end Alembic commands ###
